# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: ${SPRING_DATASOURCE_URL}
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: todo
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true